### DISCUSSION TITLE
Issue with Celery configuration

### DISCUSSION THREAD

**Discussion by danilNil** [codingjoe/joeflow#84] [Q&A]
Hi @codingjoe! Thank you for this library. It looks great! We chose it over other WFEs and tried to integrate it into our project.

We faced some issues with Celery configuration and it would be great if you could give us a hint about where the root cause is.

So we've added a workflow model, we can create a new instance in Django admin but we can not see any tasks generated in Celery. All instances are working in Docker

Please find our configs and code below. We will really appreciate your help.

cc @s-tatus

## requirements.txt

```
celery==5.2.7
Django==4.2.1
django-auth-ldap==4.3.0
djangorestframework==3.14.0
djangorestframework-simplejwt==5.2.2
drf-yasg==1.21.5
django-reversion==5.0.4
psycopg2-binary==2.9.6
pytest-django==4.5.2
pytest-mock==3.10.0
pika==1.3.2
tzdata==2023.3
joeflow[reversion,celery]==1.2.4
```

## settings.py

```
...
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.forms",
    'rest_framework',
    'drf_yasg',
    'user.apps.UserConfig',
    'opc_service.apps.OpcServiceConfig',
    "joeflow",
    "wfe",
    "reversion",
]

# Celery conf

JOEFLOW_CELERY_QUEUE_NAME = 'joeflow_queue'
JOEFLOW_TASK_RUNNER = 'joeflow.runner.celery.task_runner'

CELERY_BROKER_URL = 'amqp://rmuser:rmpassword@rabbitmq:5672'
CELERY_result_backend = 'amqp://rmuser:rmpassword@rabbitmq:5672'
CELERY_accept_content = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
```

## docker-compose.yml

```
version: '3'

services:

  ...

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./mes:/project
    environment:
      - PYTHONUNBUFFERED=0
      - DJANGO_SETTINGS_MODULE=mes.settings
    working_dir: "/project"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ftpd

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./docker/data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    restart: always

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A mes worker -B
    volumes:
      - ./mes:/project
    depends_on:
      - web
      - rabbitmq

...

```
